### ISSUE TITLE
is there any tutorial or sample code?

### ISSUE THREAD

**Issue by MahdiPishguy** [Okipa/laravel-brickables#11]
what does mean 

> allows you to associate content bricks to Eloquent models

and is there any **page/video** tutorial or sample code to understand how is it work and help us?

**Comment by Okipa** [comment]
Hi @MahdiPishguy, this package gives the ability to manage designed page parts (or content bricks) from backoffice in a CMS-way.

Of course, you have to create and design the content bricks you want to mange first.

I never took time to create any tutorial about it but I think you can easily get started by following the Readme.
